### ISSUE TITLE
Can't create directories

### ISSUE THREAD

**Issue by idolpx** [rostwolke/ESPAsyncWebdav#3]
I get a "405 Method Not Allowed" when trying to create a folder.

**Comment by idolpx** [comment]
Not sure what happened but after reflashing my LittleFS filesystem it started working.

**Comment by rostwolke** [comment]
Thank you for reporting a problem and posting the solution. I checked my code (has been a while since I last time worked on it) and saw that 405 errors occur if a directory can not be created. Glad that reflashing your filesystem helped.

**Comment by idolpx** [comment]
I really like that you implemented it using ESPAsyncWebserver.  After testing it's not going to work for me though.  It uses too much memory when creating the response and I'm getting OOM errors.  If there are only a few files in the folder it is fine.  If there was a way to flush the response out as it was being built that would solve the problem but I haven't found a way to do that yet.  I also considered writing the response to flash then streaming that.  I don't want to wear out the flash memory though.  Maybe the xml could be cached only if it's changed or something.  Still exploring options.

**Comment by rostwolke** [comment]
Good idea. Soon I will need this project again and have a look how to fix it.
