### ISSUE TITLE
Outdated AsyncWebServer + open pull request

### ISSUE THREAD

**Issue by sivar2311** [rostwolke/ESPAsyncWebdav#5]
Hi Rostwolke!

Your fork of the ESPAsyncWebServer is outdated (6 commits behind) and therefore leads to compilation errors on the ESP32.

Furthermore, there is an open pull request for this repository which allows the choice of the file system. 
Are you considering applying this (very useful) pull-request?

**Comment by rostwolke** [comment]
Hi,

Thanks for the info about the webserver. I will update it.

I am considering to apply this PR, just thinking about how to implement the quota for different file systems.

**Comment by sivar2311** [comment]
Hi @rostwolke !
Thanks for your fast reply!

What do you think about [this](https://github.com/sivar2311/ESPAsyncWebdav/commit/cd09a395f010e111d6e3ef761a6cabc07a5bcc0c) solution?

Usage:
```C++
size_t totalBytes() { return LittleFS.totalBytes(); }
size_t usedBytes() { return LittleFS.usedBytes(); }

AsyncWebServer server(80);
AsyncWebdav    dav("/dav", LittleFS, totalBytes, usedBytes);
```

Not perfect but working :)

p.s. Sonnige Grüße aus Schleswig-Holstein!

**Comment by sivar2311** [comment]
Alternatively, you could change the AsyncWebdav class to a template class like [this](https://github.com/sivar2311/ESPAsyncWebdav/blob/template/src/AsyncWebdav.h)

LittleFS Usage:
```C++
AsyncWebdav<fs::LittleFSFS> dav("/dav", LittleFS);
```

SPIFFS Usage:
```C++
AsyncWebdav<fs::SPIFFSFS> dav("/dav", SPIFFS);
```

**Comment by rostwolke** [comment]
I quite like the approach in your earlier reply. I'll implement it this way. Would be even greater if you could create a PR :-)

**Comment by rostwolke** [comment]
Updated my fork of the webserver and merged the PR
